#!/usr/bin/env python3
"""Give every part in an exported OBJ its own material, for the 3D viewer.

The prototype shows and hides individual parts of a tool block assembly through
``<model-viewer>``, whose scene-graph API reaches materials but not nodes. A CAD
export normally shares one or two materials across every body, which would make
the parts inseparable, so this rewrites the OBJ to put each ``g`` group on a
material of its own.

    python3 scripts/prepare-preview-model.py "3X Spot-Drill-Tap.obj"

It writes ``<name>-parts.obj`` and ``<name>-parts.mtl`` beside the input and
prints the assimp command that turns them into the ``.glb`` the viewer loads.
Conversion is left as a separate step rather than shelled out from here.
"""

from __future__ import annotations

import argparse
import os
from typing import List

# Distinct diffuse colours so the parts stay tellable apart in any viewer that
# ignores the runtime tinting.
PALETTE = [
    (0.60, 0.65, 0.71),
    (0.85, 0.64, 0.29),
    (0.85, 0.64, 0.29),
    (0.85, 0.64, 0.29),
]


def group_names(path: str) -> List[str]:
    names: List[str] = []
    with open(path, "r", errors="replace") as handle:
        for line in handle:
            if line.startswith("g "):
                name = line[2:].strip()
                if name not in names:
                    names.append(name)
    return names


def material_for(index: int) -> str:
    return f"part_{index}"


def write_mtl(path: str, names: List[str]) -> None:
    with open(path, "w") as handle:
        handle.write("# Generated by scripts/prepare-preview-model.py\n")
        for index, name in enumerate(names):
            r, g, b = PALETTE[index % len(PALETTE)]
            handle.write(f"\nnewmtl {material_for(index)}\n")
            handle.write(f"# part: {name}\n")
            handle.write("Ka 0.000 0.000 0.000\n")
            handle.write(f"Kd {r:.3f} {g:.3f} {b:.3f}\n")
            handle.write("Ks 0.200 0.200 0.200\n")
            handle.write("Ns 40.000\n")
            handle.write("d 1.0\n")
            handle.write("illum 2\n")


def write_obj(source: str, destination: str, mtl_name: str, names: List[str]) -> None:
    index_of = {name: index for index, name in enumerate(names)}

    with open(source, "r", errors="replace") as src, open(destination, "w") as dst:
        dst.write("# Generated by scripts/prepare-preview-model.py\n")
        dst.write(f"mtllib {mtl_name}\n")
        for line in src:
            if line.startswith("mtllib") or line.startswith("usemtl"):
                # Replaced by the per-part material emitted after each group.
                continue
            dst.write(line)
            if line.startswith("g "):
                name = line[2:].strip()
                dst.write(f"usemtl {material_for(index_of[name])}\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("obj", help="OBJ exported from CAD, parts as g groups")
    parser.add_argument("--out-dir", default=None, help="defaults to the input's folder")
    args = parser.parse_args()

    source = os.path.abspath(args.obj)
    if not os.path.isfile(source):
        print(f"No such file: {source}")
        return 1

    out_dir = os.path.abspath(args.out_dir) if args.out_dir else os.path.dirname(source)
    stem = os.path.splitext(os.path.basename(source))[0]
    obj_out = os.path.join(out_dir, f"{stem}-parts.obj")
    mtl_out = os.path.join(out_dir, f"{stem}-parts.mtl")

    names = group_names(source)
    if not names:
        print("No 'g' groups found; nothing to separate.")
        return 1

    write_mtl(mtl_out, names)
    write_obj(source, obj_out, os.path.basename(mtl_out), names)

    print(f"{len(names)} parts, one material each:")
    for index, name in enumerate(names):
        print(f"  {material_for(index)}  <-  {name}")
    print(f"\nWrote {obj_out}\n      {mtl_out}")
    print("\nNow convert it:")
    print(f'  assimp export "{obj_out}" "{os.path.join(out_dir, stem + ".glb")}"')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
